import turtle as t
import math
R = 100
a = R*(1-math.sin(18*math.pi/180))/math.cos(18*math.pi/180)
t.showturtle()
t.color('red')
t.penup()
t.goto(0,R)
t.pendown()
t.right(72)
t.forward(a)
t.left(72)
t.forward(a)
t.right(144)
t.forward(a)
t.left(72)
t.forward(a)
t.right(144)
t.forward(a)
t.left(72)
t.forward(a)
t.right(144)
t.forward(a)
t.left(72)
t.forward(a)
t.right(144)
t.forward(a)
t.left(72)
t.forward(a)
t.left(18)
t.penup()
t.goto(R,0)
t.pendown()
t.circle(R)
t.done()
